# Travis CI scripts (clojure)
language: clojure
lein: lein

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
      before_install: &fix_certs
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk10
      before_install: *fix_certs
    - jdk: openjdk11
      before_install: *fix_certs

# command to install dependencies
install: lein deps &&
  npm install &&
  lein build &&
  npx webpack --display errors-only

script: lein do clean, check, test

after_success:
  # Upload coverage data to codecov
  - codecov
notifications:
  # irc:
  #   channels: "irc.freenode.org#xxxxx"
  #   template:
  #     - "%{repository_name}@%{branch}: %{message} (%{build_url})"
  #   on_success: change
  #   on_failure: change
  email: skeptycal@gmail.com
